version: 2
updates:
  - directory: /config
    package-ecosystem: gradle
    target-branch: develop
    schedule:
      interval: weekly
  - directory: /discovery
    package-ecosystem: gradle
    target-branch: develop
    schedule:
      interval: weekly
  - directory: /gateway
    package-ecosystem: gradle
    target-branch: develop
    schedule:
      interval: weekly
