version: 2
updates:
  - directory: ./
    package-ecosystem: gradle
    target-branch: develop
    schedule:
      interval: weekly
  - directory: /config-server
    package-ecosystem: gradle
    target-branch: develop
    schedule:
      interval: weekly
  - directory: /discovery-service
    package-ecosystem: gradle
    target-branch: develop
    schedule:
      interval: weekly
  - directory: /api-gateway
    package-ecosystem: gradle
    target-branch: develop
    schedule:
      interval: weekly
